import sys, os, time
from selenium import webdriver
import chardet

def RunChrome(url):

    options = webdriver.ChromeOptions()
    options.add_argument('lang=ko_KR')

    chromedriver_path = resource_path("C:\\Users\\이상민\\Desktop\\과제\\chromedriver.exe")
    driver = webdriver.Chrome(chromedriver_path, options=options)
    driver.implicitly_wait(1)
    driver.get(url)
    driver.implicitly_wait(1)

    return driver

def resource_path(relative_path):
    try: 
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)

def ConvertNumberToComma(input):
    output = []
    for item in input:
        output.append(format(item, ','))
    return output

def FocusScrollByElement(driver, element):
    scrollElementIntoMiddle = """var viewPortHeight = Math.max(document.documentElement.clientHeight, window.innerHeight || 0);
                                         var elementTop = arguments[0].getBoundingClientRect().top;
                                         window.scrollBy(0, elementTop-(viewPortHeight/2));"""
    driver.execute_script(scrollElementIntoMiddle, element)

url = 'http://search.danawa.com/dsearch.php?query=%EB%83%89%EB%8F%99%EA%B3%BC%EC%9D%BC&adult=1&originalQuery=%EB%83%89%EB%8F%99%EA%B3%BC%EC%9D%BC&previousKeyword=%EB%AF%B9%EC%84%9C%EA%B8%B0%20%EB%82%A0&volumeType=allvs&page=1&limit=120&sort=saveDESC&list=list&boost=true&addDelivery=N&tab=main'
driver = RunChrome(url)

lowest = driver.find_elements_by_class_name("lowest");

unit = '원/100g'
priceData = []
for item in lowest:
    if unit in item.text:
        price = item.text.replace(unit,'')
        price = int(price.replace(',',''))
        priceData.append(price)

priceData.sort()
priceDataComma = ConvertNumberToComma(priceData)

print (priceDataComma)
lowestPrice = min(priceData)
lowestPriceComma = format(lowestPrice, ',')
print ("lowestPrice = " + str(lowestPriceComma) + unit)

for item in lowest:
    if str(lowestPriceComma) + unit in item.text:
        FocusScrollByElement(driver, item)
